### ISSUE TITLE
6. Create a new class PersonSequencer in Data folder.

### ISSUE THREAD

**Issue by gamo-code** [LexiconDotNet-TodoIt/TodoIt#14]
a. In PersonSequencer creates a private static int variable called personId.
b. Add a static method called nextPersonId that increment and return the next
personId value.
c. Add a static method called reset() that sets the personId variable to 0.
d. Unit test PersonSequencer.
e. Commit changes.

**Comment by Zealot0150** [comment]
Lagt till classer och testat. Verkar ok.

**Comment by gamo-code** [comment]
See pull request for corrections
