### ISSUE TITLE
Change TestPersonSequencer TestPersonId method:

### ISSUE THREAD

**Issue by thosel** [LexiconDotNet-TodoIt/TodoIt#24]
Upptäckte en grej till. När man kör testen så instansieras ju en ny testklassobjekt för varje assert. Så när du kör metoden TestPersonId så görs reset PersonSequencer mellan asserten och testet felar.

Jag prövade detta och då fungerade det för mig:

int resultOne = PersonSequencer.NextPersonId();
int resultTwo = PersonSequencer.NextPersonId();
Assert.Equal(0, resultOne);
Assert.Equal(1, resultTwo);

**Comment by Zealot0150** [comment]
Ok, byter ut det med....
